FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements.txt .

RUN pip install uv && uv pip install --system -r requirements.txt
COPY ./api/backend ./api/backend

EXPOSE 8000

CMD ["uvicorn", "api.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
