FROM python:3.11-slim-bookworm

WORKDIR /app

RUN pip install uv && uv pip install --system streamlit python-dotenv

COPY main.py .
COPY ./static ./static
COPY ./.streamlit ./.streamlit

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
